const CONFIG_URL="./data.json";
const API="https://pitchandbrew.pythonanywhere.com/api/schedule";
let CONFIG=null;
const dateInput=document.getElementById("scheduleDate"),dayTitle=document.getElementById("scheduleDay"),slotsBox=document.getElementById("scheduleSlots"),formCard=document.getElementById("bookingFormCard"),selectedSlotBox=document.getElementById("selectedSlot");
function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function displayTime(t){const[h,m]=String(t).split(":").map(Number),s=h>=12?"PM":"AM",hr=h%12||12;return `${hr}:${String(m).padStart(2,"0")} ${s}`}
function showToast(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),2800)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function brand(s){return esc(s).replace(/&amp;/g,"<span>&</span>")}
function applyConfig(c){
 CONFIG=c;document.title=c.app.name;
 document.querySelectorAll("[data-brand]").forEach(e=>e.innerHTML=brand(c.app.name));
 document.querySelector("[data-splash-subtitle]").textContent=c.app.subtitle;document.querySelector("[data-brand-tag]").textContent=c.app.subtitle;
 document.querySelector("[data-home-welcome]").textContent=c.home.welcome;document.querySelector("[data-hero-text]").textContent=c.home.heroText;
 document.querySelector("[data-book-button]").textContent=c.home.buttons.booking.title;document.querySelector("[data-book-subtitle]").textContent=c.home.buttons.booking.subtitle;
 document.querySelector("[data-cafe-button]").textContent=c.home.buttons.cafe.title;document.querySelector("[data-cafe-subtitle]").textContent=c.home.buttons.cafe.subtitle;
 document.querySelector("[data-contact-button]").textContent=c.home.buttons.contact.title;document.querySelector("[data-contact-subtitle]").textContent=c.home.buttons.contact.subtitle;
 document.getElementById("sportsStrip").innerHTML=(c.home.sports||[]).map((x,i)=>`${i?"<i>•</i>":""}<span>${esc(x)}</span>`).join("");
 for(const k of ["kicker","title"]){document.querySelector(`[data-booking-${k}]`).textContent=c.booking[k]}
 document.querySelector("[data-live-schedule]").textContent=c.booking.liveSchedule;document.querySelector("[data-check-availability]").textContent=c.booking.checkAvailability;document.querySelector("[data-available-label]").textContent=c.booking.availableLabel;document.querySelector("[data-booked-label]").textContent=c.booking.bookedLabel;document.querySelector("[data-select-date]").textContent=c.booking.selectDate;
 document.querySelector("[data-select-slot]").textContent=c.form.selectSlot;document.querySelector("[data-name-label]").textContent=c.form.nameLabel;document.querySelector("[data-name-placeholder]").placeholder=c.form.namePlaceholder;document.querySelector("[data-phone-label]").textContent=c.form.phoneLabel;document.querySelector("[data-phone-placeholder]").placeholder=c.form.phonePlaceholder;document.querySelector("[data-sport-label]").textContent=c.form.sportLabel;document.querySelector("[data-date-label]").textContent=c.form.dateLabel;document.querySelector("[data-from-label]").textContent=c.form.fromLabel;document.querySelector("[data-to-label]").textContent=c.form.toLabel;document.querySelector("[data-players-label]").textContent=c.form.playersLabel;document.querySelector("[data-players-placeholder]").placeholder=c.form.playersPlaceholder;document.querySelector("[data-message-label]").textContent=c.form.messageLabel;document.querySelector("[data-message-placeholder]").placeholder=c.form.messagePlaceholder;document.querySelector("[data-confirm-booking]").textContent=c.form.confirmButton;
 const sport=document.getElementById("sport");sport.innerHTML=`<option value="">${esc(c.form.sportPlaceholder)}</option>`+(c.form.sports||[]).map(x=>`<option>${esc(x)}</option>`).join("");
 document.querySelector("[data-cafe-kicker]").textContent=c.cafe.kicker;document.querySelector("[data-cafe-title]").textContent=c.cafe.title;document.querySelector("[data-cafe-intro]").textContent=c.cafe.intro;renderCafe();
 document.querySelector("[data-contact-kicker]").textContent=c.contact.kicker;document.querySelector("[data-contact-title]").textContent=c.contact.title;document.querySelector("[data-contact-description]").textContent=c.contact.description;document.querySelector("[data-call-title]").textContent=c.contact.callTitle;document.querySelector("[data-whatsapp-title]").textContent=c.contact.whatsappTitle;document.querySelector("[data-whatsapp-subtitle]").textContent=c.contact.whatsappSubtitle;
 document.getElementById("callButton").href=`tel:${c.contact.phone.replace(/[^\d+]/g,"")}`;document.getElementById("callNumber").textContent=c.contact.phone;document.getElementById("whatsappButton").href=`https://wa.me/${String(c.contact.whatsappNumber).replace(/\D/g,"")}?text=${encodeURIComponent(c.contact.whatsappMessage)}`;
}
const icons={chai:`<path class="svg-gold" d="M45 42h58v37c0 16-12 27-29 27S45 95 45 79V42Z"/><path class="svg-gold" d="M103 52h13c13 0 18 8 18 16s-6 15-18 15h-13"/><path class="svg-gold" d="M56 28c-8-12 8-15 0-25"/><path class="svg-gold" d="M76 28c-8-12 8-15 0-25"/><path class="svg-gold" d="M94 28c-8-12 8-15 0-25"/>`,paratha:`<circle class="svg-gold-fill" cx="75" cy="62" r="42"/><circle class="svg-dark" cx="75" cy="62" r="28"/><path class="svg-gold" d="M47 51c18 10 39 10 56 0"/><path class="svg-gold" d="M48 72c18-10 39-10 54 0"/>`,fries:`<path class="svg-gold" d="M48 42L55 98H105L112 42Z"/><path class="svg-gold" d="M55 42h50"/><path class="svg-gold" d="M60 44L54 15"/><path class="svg-gold" d="M72 44L70 8"/><path class="svg-gold" d="M84 44L86 12"/><path class="svg-gold" d="M96 44L102 16"/>`,loaded:`<path class="svg-gold" d="M60 22h30l6 80H54z"/><path class="svg-gold" d="M63 22V10h24v12"/><path class="svg-gold" d="M58 50h35"/>,lays:`<path class="svg-gold-fill" d="M48 18h54l9 84H39z"/><path class="svg-dark" d="M57 43c12-12 27 12 39 0"/><circle class="svg-gold-fill" cx="75" cy="69" r="17"/>`,cold:`<path class="svg-gold" d="M55 25h40l-5 78H60z"/><path class="svg-gold" d="M55 25h40"/><path class="svg-gold" d="M63 15h24"/><path class="svg-gold" d="M65 48h30"/><path class="svg-gold" d="M67 70h26"/>`,water:`<path class="svg-gold" d="M60 22h30l6 80H54z"/><path class="svg-gold" d="M63 22V10h24v12"/><path class="svg-gold" d="M58 50h35"/>`,juice:`<path class="svg-gold" d="M52 35h45l-7 68H59z"/><path class="svg-gold" d="M76 35L91 8"/><circle class="svg-gold" cx="75" cy="65" r="12"/>`};
function renderCafe(){document.getElementById("cafeGrid").innerHTML=(CONFIG.cafe.items||[]).map(x=>`<div class="cafe-card"><div class="food-art"><svg viewBox="0 0 150 120">${icons[x.icon]||icons.chai}</svg></div><h3>${esc(x.name)}</h3><strong>${esc(CONFIG.cafe.currency)} ${esc(x.price)}</strong></div>`).join("")}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id)?.classList.add("active");window.scrollTo({top:0,behavior:"smooth"});if(id==="bookingPage")loadSchedule()}
function resetSelected(){selectedSlotBox.classList.remove("active");selectedSlotBox.innerHTML=`<span>${esc(CONFIG?.form?.selectSlot||"SELECT AN AVAILABLE TIME ABOVE")}</span>`;formCard.classList.remove("ready");document.getElementById("fromTime").value="";document.getElementById("toTime").value=""}
function selectSlot(start,end,status){if(String(status).toLowerCase()==="booked"){showToast(CONFIG.messages.booked);return}document.getElementById("fromTime").value=start;document.getElementById("toTime").value=end;document.getElementById("date").value=dateInput.value;selectedSlotBox.classList.add("active");selectedSlotBox.textContent=`✓ SELECTED: ${displayTime(start)} – ${displayTime(end)}`;formCard.classList.add("ready");formCard.scrollIntoView({behavior:"smooth",block:"center"})}
async function loadSchedule(){const date=dateInput.value;if(!date||!CONFIG)return;resetSelected();const d=new Date(date+"T12:00:00");const day=d.toLocaleDateString("en-US",{weekday:"long"});dayTitle.textContent=day;slotsBox.innerHTML=`<div class="loading-box">${esc(CONFIG.messages.loading)}</div>`;let data;try{const r=await fetch(`${API}?date=${encodeURIComponent(date)}&_=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;data=await r.json();if(String(data.date||"")!==String(date))throw 0}catch(e){data={date,day,slots:[]}}const slots=Array.isArray(data.slots)?data.slots:[];if(!slots.length){slotsBox.innerHTML=`<div class="loading-box">${esc(CONFIG.messages.noSchedule)}</div>`;return}slotsBox.innerHTML="";slots.forEach(([start,end,status,name])=>{const booked=String(status).toLowerCase()==="booked",el=document.createElement("div");el.className=`slot ${booked?"booked":"available"}`;el.innerHTML=`<div class="slot-time">${displayTime(start)} – ${displayTime(end)}</div><div class="slot-status">${booked?"🔴 "+esc(CONFIG.booking.bookedLabel).toUpperCase():"🟢 "+esc(CONFIG.booking.availableLabel).toUpperCase()}</div>${booked&&name?`<div class="booked-by">${esc(CONFIG.booking.bookedByPrefix)} ${esc(name)}</div>`:""}`;el.onclick=()=>selectSlot(start,end,status);slotsBox.appendChild(el)})}
function sendBooking(){const name=document.getElementById("name").value.trim(),phone=document.getElementById("phone").value.trim(),sport=document.getElementById("sport").value,date=document.getElementById("date").value,from=document.getElementById("fromTime").value,to=document.getElementById("toTime").value,players=document.getElementById("players").value.trim(),message=document.getElementById("message").value.trim();if(!from||!to)return showToast(CONFIG.messages.selectTime);if(!name)return showToast(CONFIG.messages.name);if(!phone)return showToast(CONFIG.messages.phone);if(!sport)return showToast(CONFIG.messages.sport);if(!players)return showToast(CONFIG.messages.players);const formattedDate=new Date(date+"T12:00:00").toLocaleDateString("en-PK",{day:"2-digit",month:"short",year:"numeric"});let text=`*${CONFIG.booking.whatsappTitle}*\n\nName: ${name}\nPhone: ${phone}\nSport: ${sport}\nDate: ${formattedDate}\nTime: ${displayTime(from)} to ${displayTime(to)}\nPlayers: ${players}`;if(message)text+=`\n${CONFIG.form.additionalMessagePrefix}: ${message}`;text+=`\n\n${CONFIG.booking.thankYou}\n${CONFIG.app.name}\n${CONFIG.app.subtitle}`;window.location.href=`https://wa.me/${String(CONFIG.booking.whatsappNumber).replace(/\D/g,"")}?text=${encodeURIComponent(text)}`}
async function boot(){dateInput.value=todayISO();document.getElementById("date").value=dateInput.value;try{const r=await fetch(`${CONFIG_URL}?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;CONFIG=await r.json();applyConfig(CONFIG)}catch(e){showToast("Unable to load the latest app settings.");return}dateInput.addEventListener("change",loadSchedule);setTimeout(()=>document.getElementById("splashScreen")?.remove(),5100);loadSchedule()}
boot();
